### ISSUE TITLE
r23 ndk fails to download

### ISSUE THREAD

**Issue by cherryleafroad** [nttld/setup-ndk#181]
Apparently the URL changed,

https://dl.google.com/android/repository/android-ndk-r23-windows.zip

The 64 bit release now omits the ending "-x86_64". In fact, the Mac and Linux one also are this way now for r23

**Comment by raftario** [comment]
Should be fixed in the new release, sorry for the delay

**Comment by cherryleafroad** [comment]
Works great now, thanks!
