### ISSUE TITLE
NDK version is not added to Android SDK path

### ISSUE THREAD

**Issue by guillaume-tgl** [nttld/setup-ndk#432]
It seems like this action doesn't add the NDK version in the Android SDK folder as the SDK manager does it.
Indeed, it seems like Gradle is looking for NDK versions in the ANDROID_HOME folder and other [preinstalled NDK versions](preinstalled) are there too:

![Screenshot 2023-04-24 at 11 15 00](https://user-images.githubusercontent.com/2244170/233953402-5a73b982-eb80-40c5-be6e-b943efaa41e9.png)

**Comment by guillaume-tgl** [comment]
Any update?

**Comment by guillaume-tgl** [comment]
How about moving it to the SDK folder after the full version number is known?

**Comment by raftario** [comment]
That's not possible when using github's runner tool cache as this action does

**Comment by raftario** [comment]
Can you confirm whether a symlink does get recognised by Gradle ?

**Comment by kairusds** [comment]
Why not just override the Android NDK global environment variables provided by the runners?

**Comment by captainurist** [comment]
`mv` works for me:
https://github.com/OpenEnroth/OpenEnroth/actions/runs/5915697855/job/16042201851#step:6:1

`ln -s` also works:
https://github.com/OpenEnroth/OpenEnroth/actions/runs/5915703205/job/16042211902#step:6:1

Would be nice to have an option to place NDK directly to the SDK path, and have the actual NDK version number exported in one of the action's outputs.

**Comment by raftario** [comment]
An opt-in option that disables caching would work yeah, and adding an extra output should be fairly trivial. I might also open an issue in github's toolkit repo asking whether they'd be willing to make the function used to select a cache directory public

**Comment by elrinor** [comment]
I don't understand the internal workings of tool caching to argue, but even if you move it out, then it'll still be kept in github cache & restored in the next action, so not a big issue, no? At least I'm under an impression that this was what I saw in my own workflows.

And you can always just symlink it into place. I have only tested it on Linux though.

**Comment by raftario** [comment]
There's two types of caches. The one you're thinking of is probably the standard cache accessible using the `@actions/cache` action and exposed through the `local-cache` config option of this action, for which the location doesn't matter. But there's also a second cache, the tool cache, which is a special directory on the runners themselves which can be persisted across workflows on the same runner to diminish setup times. That's where pretty much all of the `setup-xyz` actions install things, and the directory structure follows a certain format internally that you can't really deviate from.

**Comment by raftario** [comment]
To be completely fair the tool cache it is only useful for self-hosted runner or when swapping between different NDK versions in the same workflow. These are more important than Gradle compatibility to me and the audience this action was initially targetting, but at this point there's a lot of people using the action for a lot of different things so it might also be worth to just nuke the tool cache support to make things simpler.
