### ISSUE TITLE
Using setup-ndk from another job

### ISSUE THREAD

**Issue by n-eq** [nttld/setup-ndk#469]
Hello, I am using setup-ndk action to define Android environment variables (mainly NDK_HOME, ANDROID_SDK), before building some source files for different targets, see the screenshot below.

![image](https://github.com/nttld/setup-ndk/assets/16545838/1d86b040-6c5f-4497-a113-2d58b8bd71d0)

However, although the installation seems OK (the environment is correctly setup)  during the `Setup Android NDK` step, it is lost in `Build Android`: the installed NDK does no more exist on the runner. Is this behavior normal? If so can you think of any solution/workaround? Thank you.

**Comment by raftario** [comment]
That's the expected behaviour of GitHub actions, each job gets its own clean environment. I'd recommend checking out the GitHub's documentation as the behaviour isn't really related to this project.
