### ISSUE TITLE
gradlew fails with NDK r26-rc1 downloaded with link-to-sdk: true

### ISSUE THREAD

**Issue by captainurist** [nttld/setup-ndk#498]
The problem I'm seeing:
* `outputs.ndk-full-version` is `26.0.10636728-beta2`.
* Path to NDK is `/usr/local/lib/android/sdk/ndk/26.0.10636728-beta2`.
* Even if I set `ndkVersion` in `build.gradle` to `26.0.10636728-beta2`, it's still looking for it in `/usr/local/lib/android/sdk/ndk/26.0.10636728`.

It looks like we need to drop any suffixes from `Pkg.Revision` before linking the NDK into Android SDK.

**Comment by captainurist** [comment]
Workflow in question:
https://github.com/OpenEnroth/OpenEnroth/actions/runs/5988409806/job/16243569824

**Comment by raftario** [comment]
Probably should've tested against a beta before pushing a release, my bad.
