### ISSUE TITLE
how to use the action with gradle?

### ISSUE THREAD

**Issue by yangcheng** [nttld/setup-ndk#74]
my build file looks like the following, however, I still get the error that `> No version of NDK matched the requested version 21.3.6528147. Versions available locally: 22.0.7026061` 

is there a good way to tell grade that a NDK version has been downloaded? Thanks 

```    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: download ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d
      - name: Generate Debug APK
        run: ./gradlew clean assembleDebug
```

**Comment by raftario** [comment]
I'm not really familiar with gradle, but this looks like it should do the trick
https://developer.android.com/studio/projects/configure-agp-ndk

**Comment by raftario** [comment]
I'm going to close this issue since it's more of a question about the usage of gradle. This action is mostly meant for fully native worflows, I feel like there are probably better ways to setup the NDK for usage in more "classic" android workflows.
